// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

/**
 * @title VaultConfig
 * @dev Configuration library for Vault deployment
 * @notice This file is auto-generated from config/vaultConfig.json for network: mainnet
 * @notice Do not edit this file directly - edit config/vaultConfig.json and run: node config/genConfig.js mainnet
 */
library VaultConfig {
    // Current Network Configuration (mainnet)
    address constant TOKEN1 = address(0x000000000000000000000000000000000006f89a);
    address constant TOKEN2 = address(0x0000000000000000000000000000000000163B5a);
    uint256 constant RUN_TIMESTAMP = 300;
    uint256 constant STOP_TIMESTAMP = 360;
    uint256 constant MAX_SHAREHOLDERS = 50;
}
